# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'SinaWeibo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~>3.0.4'
  pod 'SDWebImage', '~>3.7.5'
  pod 'SVProgressHUD', '~>1.1.3'
  pod 'SnapKit', '~>0.19.1'
end
